/**
 * AUTO-GENERATED by scripts/optimize-images.mjs
 * Regenerate with `pnpm images`.
 */
export interface ImgVariant {
  src: string;
  width: number;
}

export interface ImgManifestEntry {
  /** Preferred (WebP) large variant — for <picture> <source srcset>. */
  src: string;
  /** Fallback file at the original path/extension (broad compatibility). */
  fallback: string;
  /** Rotated output dimensions (layout ratio; avoids CLS). */
  width: number;
  height: number;
  webp: ImgVariant[];
}

export const imageManifest: Record<string, ImgManifestEntry> = {
  "/photos/ajiro_shoujin_ryouri.jpeg": {
    "src": "/photos/ajiro_shoujin_ryouri-1920.webp",
    "fallback": "/photos/ajiro_shoujin_ryouri.jpeg",
    "width": 1600,
    "height": 1200,
    "webp": [
      {
        "src": "/photos/ajiro_shoujin_ryouri-640.webp",
        "width": 640
      },
      {
        "src": "/photos/ajiro_shoujin_ryouri-960.webp",
        "width": 960
      },
      {
        "src": "/photos/ajiro_shoujin_ryouri-1440.webp",
        "width": 1440
      },
      {
        "src": "/photos/ajiro_shoujin_ryouri-1920.webp",
        "width": 1920
      }
    ]
  },
  "/photos/blue_cavern_water.jpeg": {
    "src": "/photos/blue_cavern_water-960.webp",
    "fallback": "/photos/blue_cavern_water.jpeg",
    "width": 1280,
    "height": 960,
    "webp": [
      {
        "src": "/photos/blue_cavern_water-640.webp",
        "width": 640
      },
      {
        "src": "/photos/blue_cavern_water-960.webp",
        "width": 960
      }
    ]
  },
  "/photos/central_london_view.jpeg": {
    "src": "/photos/central_london_view-1920.webp",
    "fallback": "/photos/central_london_view.jpeg",
    "width": 1600,
    "height": 1200,
    "webp": [
      {
        "src": "/photos/central_london_view-640.webp",
        "width": 640
      },
      {
        "src": "/photos/central_london_view-960.webp",
        "width": 960
      },
      {
        "src": "/photos/central_london_view-1440.webp",
        "width": 1440
      },
      {
        "src": "/photos/central_london_view-1920.webp",
        "width": 1920
      }
    ]
  },
  "/photos/edinburgh_view.jpeg": {
    "src": "/photos/edinburgh_view-1920.webp",
    "fallback": "/photos/edinburgh_view.jpeg",
    "width": 1600,
    "height": 1200,
    "webp": [
      {
        "src": "/photos/edinburgh_view-640.webp",
        "width": 640
      },
      {
        "src": "/photos/edinburgh_view-960.webp",
        "width": 960
      },
      {
        "src": "/photos/edinburgh_view-1440.webp",
        "width": 1440
      },
      {
        "src": "/photos/edinburgh_view-1920.webp",
        "width": 1920
      }
    ]
  },
  "/photos/evening_sky.jpeg": {
    "src": "/photos/evening_sky-960.webp",
    "fallback": "/photos/evening_sky.jpeg",
    "width": 1280,
    "height": 960,
    "webp": [
      {
        "src": "/photos/evening_sky-640.webp",
        "width": 640
      },
      {
        "src": "/photos/evening_sky-960.webp",
        "width": 960
      }
    ]
  },
  "/photos/fn_waterfall.jpeg": {
    "src": "/photos/fn_waterfall-960.webp",
    "fallback": "/photos/fn_waterfall.jpeg",
    "width": 1280,
    "height": 960,
    "webp": [
      {
        "src": "/photos/fn_waterfall-640.webp",
        "width": 640
      },
      {
        "src": "/photos/fn_waterfall-960.webp",
        "width": 960
      }
    ]
  },
  "/photos/himeji_castle.jpeg": {
    "src": "/photos/himeji_castle-1920.webp",
    "fallback": "/photos/himeji_castle.jpeg",
    "width": 1600,
    "height": 2134,
    "webp": [
      {
        "src": "/photos/himeji_castle-640.webp",
        "width": 640
      },
      {
        "src": "/photos/himeji_castle-960.webp",
        "width": 960
      },
      {
        "src": "/photos/himeji_castle-1440.webp",
        "width": 1440
      },
      {
        "src": "/photos/himeji_castle-1920.webp",
        "width": 1920
      }
    ]
  },
  "/photos/kamakura_view.jpeg": {
    "src": "/photos/kamakura_view-1920.webp",
    "fallback": "/photos/kamakura_view.jpeg",
    "width": 1600,
    "height": 2133,
    "webp": [
      {
        "src": "/photos/kamakura_view-640.webp",
        "width": 640
      },
      {
        "src": "/photos/kamakura_view-960.webp",
        "width": 960
      },
      {
        "src": "/photos/kamakura_view-1440.webp",
        "width": 1440
      },
      {
        "src": "/photos/kamakura_view-1920.webp",
        "width": 1920
      }
    ]
  },
  "/photos/kyoto_garden.jpeg": {
    "src": "/photos/kyoto_garden-960.webp",
    "fallback": "/photos/kyoto_garden.jpeg",
    "width": 1280,
    "height": 960,
    "webp": [
      {
        "src": "/photos/kyoto_garden-640.webp",
        "width": 640
      },
      {
        "src": "/photos/kyoto_garden-960.webp",
        "width": 960
      }
    ]
  },
  "/photos/lake_biwa_michigan_ship.jpeg": {
    "src": "/photos/lake_biwa_michigan_ship-1920.webp",
    "fallback": "/photos/lake_biwa_michigan_ship.jpeg",
    "width": 1600,
    "height": 1230,
    "webp": [
      {
        "src": "/photos/lake_biwa_michigan_ship-640.webp",
        "width": 640
      },
      {
        "src": "/photos/lake_biwa_michigan_ship-960.webp",
        "width": 960
      },
      {
        "src": "/photos/lake_biwa_michigan_ship-1440.webp",
        "width": 1440
      },
      {
        "src": "/photos/lake_biwa_michigan_ship-1920.webp",
        "width": 1920
      }
    ]
  },
  "/photos/london_view.jpeg": {
    "src": "/photos/london_view-1920.webp",
    "fallback": "/photos/london_view.jpeg",
    "width": 1600,
    "height": 1200,
    "webp": [
      {
        "src": "/photos/london_view-640.webp",
        "width": 640
      },
      {
        "src": "/photos/london_view-960.webp",
        "width": 960
      },
      {
        "src": "/photos/london_view-1440.webp",
        "width": 1440
      },
      {
        "src": "/photos/london_view-1920.webp",
        "width": 1920
      }
    ]
  },
  "/photos/my_portrait.jpeg": {
    "src": "/photos/my_portrait-960.webp",
    "fallback": "/photos/my_portrait.jpeg",
    "width": 1280,
    "height": 1280,
    "webp": [
      {
        "src": "/photos/my_portrait-640.webp",
        "width": 640
      },
      {
        "src": "/photos/my_portrait-960.webp",
        "width": 960
      }
    ]
  },
  "/photos/nakafurano.jpeg": {
    "src": "/photos/nakafurano-960.webp",
    "fallback": "/photos/nakafurano.jpeg",
    "width": 1280,
    "height": 960,
    "webp": [
      {
        "src": "/photos/nakafurano-640.webp",
        "width": 640
      },
      {
        "src": "/photos/nakafurano-960.webp",
        "width": 960
      }
    ]
  },
  "/photos/nara_kasuga_taisha.jpeg": {
    "src": "/photos/nara_kasuga_taisha-1920.webp",
    "fallback": "/photos/nara_kasuga_taisha.jpeg",
    "width": 1600,
    "height": 2133,
    "webp": [
      {
        "src": "/photos/nara_kasuga_taisha-640.webp",
        "width": 640
      },
      {
        "src": "/photos/nara_kasuga_taisha-960.webp",
        "width": 960
      },
      {
        "src": "/photos/nara_kasuga_taisha-1440.webp",
        "width": 1440
      },
      {
        "src": "/photos/nara_kasuga_taisha-1920.webp",
        "width": 1920
      }
    ]
  },
  "/photos/osaka_castle.jpeg": {
    "src": "/photos/osaka_castle-1920.webp",
    "fallback": "/photos/osaka_castle.jpeg",
    "width": 1600,
    "height": 1200,
    "webp": [
      {
        "src": "/photos/osaka_castle-640.webp",
        "width": 640
      },
      {
        "src": "/photos/osaka_castle-960.webp",
        "width": 960
      },
      {
        "src": "/photos/osaka_castle-1440.webp",
        "width": 1440
      },
      {
        "src": "/photos/osaka_castle-1920.webp",
        "width": 1920
      }
    ]
  },
  "/photos/otaru_sea.jpeg": {
    "src": "/photos/otaru_sea-960.webp",
    "fallback": "/photos/otaru_sea.jpeg",
    "width": 1280,
    "height": 960,
    "webp": [
      {
        "src": "/photos/otaru_sea-640.webp",
        "width": 640
      },
      {
        "src": "/photos/otaru_sea-960.webp",
        "width": 960
      }
    ]
  },
  "/photos/otaru_view.jpeg": {
    "src": "/photos/otaru_view-1920.webp",
    "fallback": "/photos/otaru_view.jpeg",
    "width": 1600,
    "height": 1200,
    "webp": [
      {
        "src": "/photos/otaru_view-640.webp",
        "width": 640
      },
      {
        "src": "/photos/otaru_view-960.webp",
        "width": 960
      },
      {
        "src": "/photos/otaru_view-1440.webp",
        "width": 1440
      },
      {
        "src": "/photos/otaru_view-1920.webp",
        "width": 1920
      }
    ]
  },
  "/photos/tokyo_shobu.jpeg": {
    "src": "/photos/tokyo_shobu-960.webp",
    "fallback": "/photos/tokyo_shobu.jpeg",
    "width": 1280,
    "height": 960,
    "webp": [
      {
        "src": "/photos/tokyo_shobu-640.webp",
        "width": 640
      },
      {
        "src": "/photos/tokyo_shobu-960.webp",
        "width": 960
      }
    ]
  },
  "/photos/tokyo_view.jpeg": {
    "src": "/photos/tokyo_view-960.webp",
    "fallback": "/photos/tokyo_view.jpeg",
    "width": 1280,
    "height": 960,
    "webp": [
      {
        "src": "/photos/tokyo_view-640.webp",
        "width": 640
      },
      {
        "src": "/photos/tokyo_view-960.webp",
        "width": 960
      }
    ]
  },
  "/photos/toyama_downtown.jpeg": {
    "src": "/photos/toyama_downtown-960.webp",
    "fallback": "/photos/toyama_downtown.jpeg",
    "width": 960,
    "height": 1280,
    "webp": [
      {
        "src": "/photos/toyama_downtown-640.webp",
        "width": 640
      },
      {
        "src": "/photos/toyama_downtown-960.webp",
        "width": 960
      }
    ]
  },
  "/photos/waseda_university.jpeg": {
    "src": "/photos/waseda_university-1920.webp",
    "fallback": "/photos/waseda_university.jpeg",
    "width": 1600,
    "height": 2134,
    "webp": [
      {
        "src": "/photos/waseda_university-640.webp",
        "width": 640
      },
      {
        "src": "/photos/waseda_university-960.webp",
        "width": 960
      },
      {
        "src": "/photos/waseda_university-1440.webp",
        "width": 1440
      },
      {
        "src": "/photos/waseda_university-1920.webp",
        "width": 1920
      }
    ]
  },
  "/images/clear_aligner_app_work_sample.png": {
    "src": "/images/clear_aligner_app_work_sample-1920.webp",
    "fallback": "/images/clear_aligner_app_work_sample.png",
    "width": 1600,
    "height": 915,
    "webp": [
      {
        "src": "/images/clear_aligner_app_work_sample-640.webp",
        "width": 640
      },
      {
        "src": "/images/clear_aligner_app_work_sample-960.webp",
        "width": 960
      },
      {
        "src": "/images/clear_aligner_app_work_sample-1440.webp",
        "width": 1440
      },
      {
        "src": "/images/clear_aligner_app_work_sample-1920.webp",
        "width": 1920
      }
    ]
  },
  "/images/devcred_home.png": {
    "src": "/images/devcred_home-1920.webp",
    "fallback": "/images/devcred_home.png",
    "width": 1600,
    "height": 950,
    "webp": [
      {
        "src": "/images/devcred_home-640.webp",
        "width": 640
      },
      {
        "src": "/images/devcred_home-960.webp",
        "width": 960
      },
      {
        "src": "/images/devcred_home-1440.webp",
        "width": 1440
      },
      {
        "src": "/images/devcred_home-1920.webp",
        "width": 1920
      }
    ]
  },
  "/images/devcred_job_fair_coding_tournament.png": {
    "src": "/images/devcred_job_fair_coding_tournament-1920.webp",
    "fallback": "/images/devcred_job_fair_coding_tournament.png",
    "width": 1600,
    "height": 951,
    "webp": [
      {
        "src": "/images/devcred_job_fair_coding_tournament-640.webp",
        "width": 640
      },
      {
        "src": "/images/devcred_job_fair_coding_tournament-960.webp",
        "width": 960
      },
      {
        "src": "/images/devcred_job_fair_coding_tournament-1440.webp",
        "width": 1440
      },
      {
        "src": "/images/devcred_job_fair_coding_tournament-1920.webp",
        "width": 1920
      }
    ]
  },
  "/images/tabelog-ml-img.png": {
    "src": "/images/tabelog-ml-img-1920.webp",
    "fallback": "/images/tabelog-ml-img.png",
    "width": 1600,
    "height": 908,
    "webp": [
      {
        "src": "/images/tabelog-ml-img-640.webp",
        "width": 640
      },
      {
        "src": "/images/tabelog-ml-img-960.webp",
        "width": 960
      },
      {
        "src": "/images/tabelog-ml-img-1440.webp",
        "width": 1440
      },
      {
        "src": "/images/tabelog-ml-img-1920.webp",
        "width": 1920
      }
    ]
  },
  "/images/tabelog_ml_app_img_1.png": {
    "src": "/images/tabelog_ml_app_img_1-1920.webp",
    "fallback": "/images/tabelog_ml_app_img_1.png",
    "width": 1600,
    "height": 1040,
    "webp": [
      {
        "src": "/images/tabelog_ml_app_img_1-640.webp",
        "width": 640
      },
      {
        "src": "/images/tabelog_ml_app_img_1-960.webp",
        "width": 960
      },
      {
        "src": "/images/tabelog_ml_app_img_1-1440.webp",
        "width": 1440
      },
      {
        "src": "/images/tabelog_ml_app_img_1-1920.webp",
        "width": 1920
      }
    ]
  },
  "/images/tabelog_ml_app_img_2.png": {
    "src": "/images/tabelog_ml_app_img_2-1920.webp",
    "fallback": "/images/tabelog_ml_app_img_2.png",
    "width": 1600,
    "height": 1040,
    "webp": [
      {
        "src": "/images/tabelog_ml_app_img_2-640.webp",
        "width": 640
      },
      {
        "src": "/images/tabelog_ml_app_img_2-960.webp",
        "width": 960
      },
      {
        "src": "/images/tabelog_ml_app_img_2-1440.webp",
        "width": 1440
      },
      {
        "src": "/images/tabelog_ml_app_img_2-1920.webp",
        "width": 1920
      }
    ]
  }
};
